### ISSUE TITLE
ibm-platform-services is not compatible with ibm-cos-sdk-config which is >1.1.0 version.

### ISSUE THREAD

**Issue by Andras-Csanyi** [IBM/ibm-cos-sdk-python-config#1]
@lokeshdubeyin opened the ticket mentioned below in the [platform-services-python-sdk](https://github.com/IBM/platform-services-python-sdk) repo which is about that ibm-cos-sdk-python-config package requires an old version from python-sdk-core then platform-services-python-sdk.
Please find the details [here](https://github.com/IBM/platform-services-python-sdk/issues/132).

**Comment by lokeshdubeyin** [comment]
Hello, just wondering if we have an update on this issue. @IBMeric

**Comment by lokeshdubeyin** [comment]
@paul-carron @rtveitch

**Comment by IBMeric** [comment]
There is no update besides the one already provided: this is a long-term roadmap item that is being addressed. The required changes are user-breaking, so we would have to release a v2 version of the SDK. Because of the additional work required for a new major version, I cannot give you a delivery date, but it is safe to say it is not something to expect in the coming weeks.

The simplest workaround is not to use both SDKs in the same project but instead have separate applications. This is usual solution based on internal user reports.

**Comment by losdevnull** [comment]
We have the same problem with ibm-cloudant-sdk and ibm-cos-sdk-config requiring incompatible version of  ibm_cloud_sdk_core.   Are there any update for a v2 version of this cos config sdk after months?

**Comment by IBMeric** [comment]
Thanks for your message. We've been working on an upgrade in a different language and are still resolving some issues there. Once that work is complete, Python is the next logical choice.

**Comment by IBMalok** [comment]
@Andras-Csanyi @losdevnull @lokeshdubeyin 
Hi All, 
We successfully released the` ibm-cos-sdk-config-v2.0.0` version, which makes use of the most latest ibm-cloud-sdk-core version. 
And also update your application before moving to the v2 version because the v2 version has user-breaking changes. 

[Migration guide](https://github.com/IBM/ibm-cos-sdk-python-config/blob/master/MIGRATION-V1.md)

**Comment by Andras-Csanyi** [comment]
Hey @IBMalok,
I'm not with IBM anymore and unfortunately, I cannot help you in this case. Let me tag @padamstx and @pyrooka I believe they can help you.

**Comment by padamstx** [comment]
@IBMalok If you need anything else from the SDK squad, just let us know.

cc: @dpopp07

**Comment by IBMalok** [comment]
I'm closing this ticket because the issue has been fixed.
